# For full config, please check https://github.com/georchestra/data-api/blob/main/postgis.md
#postgis:
#  schemas:
#    include:
#      - schema: "psc"
#        alias: "psc-alias"

cors:
  allowed-origins: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
